### ISSUE TITLE
In async clients, silently subscribe when first callback is added, as we now do in threading client

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#176]
#161 stores the entire history of subscription readings until the next callback is added. Unless I am missing something that will lead to OutofMemory errors for long-running clients. I think we only need to cache the single most recent reading and feed that to any new callbacks.

**Comment by klauer** [comment]
It should be only for the first subscription. Due to how the new subscription API works, there's a chance you won't get the first event unless this is done.

EPICS-monitor-wise, it's assumed you'll always get the first `EventAddResponse` callback, so I think it's worth some level of complexity here.

**Comment by danielballan** [comment]
In the threading client, we avoid this problem by only sending `EventAddRequest` when (i.e. immediately after) the first user callback is added to a subscription. Therefore, the first callback is guaranteed not to miss the first update. From then on, we only cache the most recent update, so that we can immediately pass it to any additional callbacks when they are added.

I will leave this issue open as a reminder to review the behavior of the other clients.

**Comment by klauer** [comment]
This is good in the asyncio client, and the other clients no longer exist.
