### ISSUE TITLE
Modular IOC proof-of-concept

### ISSUE THREAD

**Issue by bl0x** [caproto/caproto#428]
This is not a single issue, but rather a complicated way of asking, if this can be done in an easier way:

Based on the dynamic IOC example, I've come up with a proof-of-concept for a modular / composable IOC, that can be generated on the fly and perhaps based on a configuration file / settings / user input.

[Code is here](https://github.com/bl0x/caproto_server_modular_example)

How it works:
- Module parts of the IOC derive from PVDict and generate their own pvproperty dict.
- exportPVs() function then updates the main pv dict, which is then given to the type() call, when creating the final IOC class (FullIOC here).

A few hoops I had to go through:

1) Functions declared in the modular parts (Users or Machines) are finally called in the scope of the pvproperty, which is then part of the FullIOC. One needs to somehow propagate the modular part instance to the pvproperty. This is done now in a hackish way via the __doc__ attribute.

2) Functions needing access to objects outside their own module's scope have no means of doing so. I've added a message queue to the FullIOC where the function can put a message. This message is then picked up and handled by a separate thread.

What would be nice:
For 1) Add a 'context' or 'data' argument to the pvproperty that can be used instead of __doc__.
For 2) I don't really have any better solution...

What I tried as well:
- Use a SubGroup instead of a dict of pvproperties when exporting the PVs from the modular parts. This didn't work, because a SubGroup cannot be parameterised (cannot take any arguments). E.g. for each User I'd have to make a completely new User class.
- Use a generic SubGroup for each modular part, and then try to alter the values at runtime of the IOC. But that feels like a much bigger crutch.

Has anyone had similar issues or wanted to do the same?
Am I completely on the wrong track?
Can this be done much easier?

**Comment by bl0x** [comment]
Hi @klauer, thanks a lot for your input. Now I see a bit more clearly, how one can work with dynamic PVGroups. I'm pretty new to the coroutine programming in python, so I also have a few more questions below...

My goal is currently to write an application that is split into a few parts and each part should export a handful of its own PVs. How many parts exist and how many PVs each part has is up to the configuration of the application.

Each part of the application should be able to send messages back to a 'main' part that handles these messages, which in turn could lead to changes in the PVs of other parts.

My first intuition was to keep the code deriving from PVGroup separate from the rest of the part-class (e.g. User or Machine). This leads to needing two classes per part, as in bl0x/caproto_server_modular_example@a1fc912c7818996d10660849a2a5461955b751d3. I'm not yet sure what is larger: The advantage of cleaner separation, or the disadvantage of more things to take care of.

All the examples for both curio and caproto take it as a given, that the run() function is the only thing that is running. I haven't yet seen an example where the IOC is just one part of a much larger application. Currently, I go about it by starting the IOC from a new thread.

Also, when synchronous code (e.g. from the main message handler) needs to write() to a PV, that does not work in a straightforward way. How would I best go about that? Is it preferable to use a caproto client? Or should I use whatever means curio provides to do the communication (UniversalEvent, UniversalQueue)? Or could the PV startup function wait for a change of another value and then update the PV via write()?

**Comment by tacaswell** [comment]
What is this application?  Is this a desktop GUI application or a web application?

Does your larger application need access to the internal state of the IOC?  If not starting the caproto IOC in the sub-process and then only communicating with it via epics may be a good idea.

All of the server examples assume they are the only thing running because that is the typical use case.  There is one instance of the event loop running on the one thread and it is the event loop's responsibility to handle the (cooperative) multi-tasking.  This brings many nice things (like not having to lock agressively as you know you will not be messed with between calls to `await`).  Once you bring threads in you are in the world of pre-emptive multi tasking and things get harder.  Using something like `UniversalQueue` is nice because it has both sync/async `put` and `get` methods so you each side can interact with it 'naturally' and it internally handles the locking / bridging issues.  You could then have a task running on the event loop which was listening to the queue and either making co-routine calls directly (or spawn new tasks).

The other option is to write your whole application as an async application where the Event Loop really does run the show.  At that point you probably want to not use our `run()` function but look at what they are doing inside so you can start the extra tasks you will need for your logic.

There is an asyncio-on-qt-eventloop implementation (quamash) that manages at asyncio eventloop via the Qt event loop (I think @mattgibbs tried this with caproto?).  If you are using Qt that may be a good option too.

I strongly suggest reading https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/ which lays out a lot of the ideas around the async view of the very nicely.

https://github.com/matplotlib/matplotlib/pull/4779 may also be helpful for understanding event loops in general.

**Comment by klauer** [comment]
Closing stale issue. If you have more to add, please re-open.
