### ISSUE TITLE
Server exits when internally value written into PV exceeds limits

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#559]
I have a PV created with caproto. I have set limits on it. I am getting an error and server exits when I am trying to write the value beyond limits. This seems to be a bug. The server shouldn't exit if a user typed number outside limits.

```
[E 01:45:56.943          server:  279] Server error. Will shut down

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/asyncio/server.py", line 266, in run
        await asyncio.gather(*tasks)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/server.py", line 137, in _server_sta
rtup
        return await self.startup(self, async_lib)
      File "/Users/femto-13/All-Projects-on-femto/LaserLab/Software/caproto-sandbox/caproto_sandbox/example_1_motor.py", line 54, in running
        await self.RBV.write(value)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/_data.py", line 484, in write
        modified_value = await self.verify_value(value)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/server.py", line 129, in verify_valu
e
        value = await super().verify_value(value)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/_data.py", line 814, in verify_value
        f"Cannot write data {val}. Limits are set to "
    caproto._data.CannotExceedLimits: Cannot write data 8.0. Limits are set to -3.0 and 7.0.
[I 01:45:56.949          server:  282] Server exiting....
```

**Comment by danielballan** [comment]
Ouch. Definitely a bug.

**Comment by danielballan** [comment]
The server definitely should not crash in response to a _client request_. When we process a `WriteRequest` or `WriteNotifyRequest` from the _client_ we do catch any errors that arise from trying to handle that request and send an `ErrorResponse` back with the details.

https://github.com/caproto/caproto/blob/f2cf563a55fc0cfe92da97a66d34b1e374e81073/caproto/server/common.py#L479-L495

From the traceback it looks like you are writing from inside the server. Now it becomes your job to manage error handling. If you try to write a value outside the limits, it's not clear what caproto should do. Should it silently ignore the request? Should it clip the value to the allowed range and go there instead? Without more information, we cannot guess what to do; guessing could result in very confusing behavior. Thus, we raise an exception that must be caught by the caller to tell us what to do next. If nothing catches the exception, we crash because anything less would be tantamount to ignoring the request.

**Comment by vstadnytskyi** [comment]
It was very late at night and indeed I was writing inside caproto server. I wrote a dummy to emulate behavior of a motor. I have two PVs: RBV and VAL. When a client writes into VAL, I set RBV to the same number. The mistake was in setting limits for RBV and not VAL. So, caproto was accepting the new set value and tried to update RBV which had a limit one it. Obviously this is wrong logic on my side. I have corrected my limits to correct ones. So now the server rejects input set value that is beyond limits.

```
    RBV = pvproperty(value=0.0,
                    read_only = True,
                    upper_alarm_limit=6.0,
                    lower_alarm_limit=-1.0,
                    upper_warning_limit=5.5,
                    lower_warning_limit=-1.0,
                    units="mm",
                    precision=3,
                    doc='motor position')
    VAL = pvproperty(value=0.0,
                    upper_alarm_limit=6.0,
                    lower_alarm_limit=-1.0,
                    upper_warning_limit=5.5,
                    lower_warning_limit=-1.0,
                    upper_ctrl_limit=7.0,
                    lower_ctrl_limit=-3.0,
                    units="mm",
                    precision=3,
                    doc='motor position')
```
And putter function
```
    @VAL.putter
    async def VAL(self, instance, value):
        print('VAL getter',value)
        await self.put_queue.async_put({'pv':'RBV','value':value})
```

**Comment by danielballan** [comment]
Sounds good. Thanks for sharing the link as a resource to others who land here. I'm going to close this issue then. Please feel free to reopen if more discussion is beneficial.
