### ISSUE TITLE
braces in PV names requires 4 sets of braces in prefix 

### ISSUE THREAD

**Issue by JunAishima** [caproto/caproto#563]
```py
#!/usr/bin/env python3

from caproto.server import pvproperty, PVGroup, ioc_arg_parser, run

class ZebraIOC(PVGroup):
    PC_DIR = pvproperty(value=1, mock_record='ai')
    PC_PULSE_STEP = pvproperty(value=10, mock_record='ai')

if name == 'main':
    ioc_options, run_options = ioc_arg_parser(
        default_prefix="C-ES:FMX{{{{Zeb:3}}}}:",
        desc='run an IOC to mock the Zebra box')
    ioc = ZebraIOC(**ioc_options)
    print('PVs:', list(ioc.pvdb))
    run(ioc.pvdb, **run_options)
```

Using 3 or fewer pairs of braces in the prefix C-ES:FMX{Zeb:3}: results in the following output:

`(local_lsdc) [jaishima@130-199-219-91 ophjects]$ python test2.py /home/jaishima/anaconda3/envs/local_lsdc/lib/python3.7/site-packages/caproto/_utils.py:246: UserWarning: EPICS_CA_ADDR_LIST is set but will be ignored because EPICS_CA_AUTO_ADDR_LIST is not set to 'no'. EPICS_CA_ADDR_LIST='127.0.0.1' EPICS_CA_AUTO_ADDR_LIST='' result.get('EPICS_CA_AUTO_ADDR_LIST', '')) Traceback (most recent call last): File "test2.py", line 13, in <module> ioc = ZebraIOC(**ioc_options) File "/home/jaishima/anaconda3/envs/local_lsdc/lib/python3.7/site-packages/caproto/server/server.py", line 1144, in __init__ self.prefix = expand_macros(prefix, self.macros) File "/home/jaishima/anaconda3/envs/local_lsdc/lib/python3.7/site-packages/caproto/server/server.py", line 975, in expand_macros return pv.format(**macros) KeyError: 'Zeb' `

**Comment by JunAishima** [comment]
to be fair, just doing this from the commandline caused the same problem

```
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> '{{{Zeb}}}'.format()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'Zeb'
```

**Comment by tacaswell** [comment]
Maybe we need a thing like `re.escape` to mark pv names that should not be formatted?

**Comment by klauer** [comment]
I think customizing how macros are expanded may work best for facilities that made poor naming standard choices: https://github.com/caproto/caproto/blob/fd540661a88f3db8b1e4f5b6942e05336f599f74/caproto/server/server.py#L1008-L1010

We could move this to a per-PVGroup level, perhaps, or provide a better hook than monkeypatching the function.

**Comment by jklynch** [comment]
I agree that poor naming standard choices have been made by one or more facilities. On the other hand this macro expansion feature could have been designed to work in the "usual" python string formatting way so that double braces escape the special single-brace behavior.

It looks to me like because macro expansion is applied to each PV prefix, every prefix string above the bottom level will be expanded more than once. If expansion were applied to PV suffixes instead then I think each string would be expanded only once and the double-brace string formatting escape hatch would work.

Gory details of the current implementation that are probably not interesting to most:

Printing the inner workings of `expand_macros` shows what goes on now (in cases where expansion raises an exception my modified `expand_macros` cheats by returning the un-expanded prefix):

Using single braces as at NSLS-II fails quickly:
```
$ python simulated_perkin_elmer_detector_ioc.py --prefix "XF:07BM-ES{Det:PE1}" --camera cam1
formatting XF:07BM-ES{Det:PE1} with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}
formatting XF:07BM-ES{Det:PE1}:TIFF1 with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}:TIFF1
formatting XF:07BM-ES{Det:PE1}:TIFF1:FileName with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}:TIFF1:FileName
formatting XF:07BM-ES{Det:PE1}:{camera}:PortName_RBV with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}:{camera}:PortName_RBV
```

In the best of all possible worlds doubling the braces around non-macros would work, and it does work for the first level of expansion but not the following levels:
```
$ python simulated_perkin_elmer_detector_ioc.py --prefix "XF:07BM-ES{{Det:PE1}}" --camera cam1
formatting XF:07BM-ES{{Det:PE1}} with {'camera': 'cam1'}
  success - return XF:07BM-ES{Det:PE1}
formatting XF:07BM-ES{Det:PE1}:TIFF1 with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}:TIFF1
formatting XF:07BM-ES{Det:PE1}:TIFF1:FileName with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}:TIFF1:FileName
formatting XF:07BM-ES{Det:PE1}:{camera}:PortName_RBV with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}:{camera}:PortName_RBV
```

4-bracing (2^2-bracing) "succeeds" for 2 levels in the sense that no exception is raised, but some PVs have double braces in them and so are incorrect.
```
$ python simulated_perkin_elmer_detector_ioc.py --prefix "XF:07BM-ES{{{{Det:PE1}}}}" --camera cam1
formatting XF:07BM-ES{{{{Det:PE1}}}} with {'camera': 'cam1'}
  success - return XF:07BM-ES{{Det:PE1}}
formatting XF:07BM-ES{{Det:PE1}}:TIFF1 with {'camera': 'cam1'}
  success - return XF:07BM-ES{Det:PE1}:TIFF1
formatting XF:07BM-ES{Det:PE1}:TIFF1:FileName with {'camera': 'cam1'}
  failure - return XF:07BM-ES{Det:PE1}:TIFF1:FileName
formatting XF:07BM-ES{{Det:PE1}}:{camera}:PortName_RBV with {'camera': 'cam1'}
  success - return XF:07BM-ES{Det:PE1}:cam1:PortName_RBV
```

8-bracing (2^3-bracing) "succeeds" for three levels (but again many PVs have too many braces):
```
$ python simulated_perkin_elmer_detector_ioc.py --prefix "XF:07BM-ES{{{{{{{{Det:PE1}}}}}}}}"  --camera cam1
formatting XF:07BM-ES{{{{{{{{Det:PE1}}}}}}}} with {'camera': 'cam1'}
  success - return XF:07BM-ES{{{{Det:PE1}}}}
formatting XF:07BM-ES{{{{Det:PE1}}}}:TIFF1 with {'camera': 'cam1'}
  success - return XF:07BM-ES{{Det:PE1}}:TIFF1
formatting XF:07BM-ES{{Det:PE1}}:TIFF1:FileName with {'camera': 'cam1'}
  success - return XF:07BM-ES{Det:PE1}:TIFF1:FileName
formatting XF:07BM-ES{{{{Det:PE1}}}}:{camera}:PortName_RBV with {'camera': 'cam1'}
  success - return XF:07BM-ES{{Det:PE1}}:cam1:PortName_RBV
```
