### ISSUE TITLE
connection_state_callback registered twice in `caproto.threading.client`

### ISSUE THREAD

**Issue by pklaus** [caproto/caproto#607]
`caproto.threading.client.Context().get_pvs()` registers a `connection_state_callback` twice if the PV instance is newly created.

### Steps to Reproduce

In one terminal start an example IOC:
```bash
python -m caproto.ioc_examples.simple --list-pvs
```
Now, when running the following Python code, the callback `connection()` is called twice:
```python
import caproto, caproto.threading

ctx = caproto.threading.client.Context()

def connection(pv, state):
    print(f"### {pv.name} {state}")

simple_A = ctx.get_pvs("simple:A", connection_state_callback=connection)
```
as the output reveals:
```
### simple:A connected
### simple:A connected
```

**Expected behaviour:**
Above output only once.

### Analysis and Potential Fix

The problem seems to be that the in `Content.get_pvs()` PV objects are [instantiated with the callback `connection_state_callback` in the __init__() call](https://github.com/caproto/caproto/blob/v0.5.1b1/caproto/threading/client.py#L1039) and a few lines later, the callback is added again manually using [`add_callback()`](https://github.com/caproto/caproto/blob/v0.5.1b1/caproto/threading/client.py#L1045).

A potential fix:

```diff
diff --git a/caproto/threading/client.py b/caproto/threading/client.py
index f6cd19a..46036f4 100644
--- a/caproto/threading/client.py
+++ b/caproto/threading/client.py
@@ -1036,8 +1036,7 @@ class Context:
                 try:
                     pv = self.pvs[(name, priority)]
                 except KeyError:
-                    pv = PV(name, priority, self, connection_state_callback,
-                            access_rights_callback, timeout)
+                    pv = PV(name, priority, self, None, None, timeout)
                     names_to_search.append(name)
                     self.pvs[(name, priority)] = pv
                     self.pvs_needing_circuits[name].add(pv)
```

or:

```diff
diff --git a/caproto/threading/client.py b/caproto/threading/client.py
index f6cd19a..17fda79 100644
--- a/caproto/threading/client.py
+++ b/caproto/threading/client.py
@@ -1035,20 +1035,18 @@ class Context:
             with self.pv_cache_lock:
                 try:
                     pv = self.pvs[(name, priority)]
+                    if connection_state_callback is not None:
+                        pv.connection_state_callback.add_callback(
+                            connection_state_callback, run=True)
+                    if access_rights_callback is not None:
+                        pv.access_rights_callback.add_callback(
+                            access_rights_callback, run=True)
                 except KeyError:
                     pv = PV(name, priority, self, connection_state_callback,
                             access_rights_callback, timeout)
                     names_to_search.append(name)
                     self.pvs[(name, priority)] = pv
                     self.pvs_needing_circuits[name].add(pv)
-
-            if connection_state_callback is not None:
-                pv.connection_state_callback.add_callback(
-                    connection_state_callback, run=True)
-            if access_rights_callback is not None:
-                pv.access_rights_callback.add_callback(
-                    access_rights_callback, run=True)
-
             pvs.append(pv)
```

Which of the fixes is better? I don't know. Maybe the second option is better if it is important that the callback is already registered, right when the object is instantiated (eg. if a state change could be missed otherwise). This is for you to judge.

**Comment by danielballan** [comment]
Thanks, @pklaus.

I think this raises a related and potentially stickier issue. What should happen when the user does:

```py
a1 = ctx.get_pvs('simple:A', connection_state_callback=f)
...
a2, b2 = ctx.get_pvs('simple:A', 'simple:B', connection_state_callback=f)
```

By caching `PV` instances, caproto ensures a given Python process only has one `PV` object for a given PV on the server to manage that channel and its associated subscriptions. Thus, in this example, `a1 is a2`.

By accepting `connection_state_callback` in `get_pvs` we've created a weird situation where when you ask for a PV the second time, the same callback `f` will be registered twice for `simple:A`.

Should we try to recognize duplicate callbacks and ignore them? For _functions_ we could do that by checking `f in [ref() for ref in pv.connection_state_callback.callbacks.values()]` but that wouldn't work for _methods_. And it's not obvious to me that it would be a good thing to silently ignore attempts to double-register.

If instead of permanently adding a callback to a long-lived registry, we exposed a _single-shot_ callback that was called once and then discarded, we would avoid accumulating callbacks. For example, `on_connect` could accept a function that is called exactly once---either when the PV connects or immediately if it is already cached and connected.

```py
a1 = ctx.get_pvs('simple:A', on_connect=f)
...
a2, b2 = ctx.get_pvs('simple:A', 'simple:B', on_connect=f)
```

Any additional long-lasting callbacks (`connection_state_callback` and `access_rights_callback`) could be added separately after instantiation, and it would be up to the user code to manage doing this once per PV...or as many times as it wants per PV, I suppose.

cc @klauer, @tacaswell, @MikeHart85

**Comment by tacaswell** [comment]
I'm in favor of adding as many copies of the callback as the user asks us to register.  I am more worried about getting the duplicate detection wrong (when the user can't do anything to work around the issue) than in being literal about what the user told us to do (where if they don't want N copies of the callback registered they can avoid it by changing their code to do be more careful about their book keeping and only register the callback once.

I have a slight preference for option 2.

**Comment by danielballan** [comment]
What’s option 2?

**Comment by tacaswell** [comment]
the second of the two diffs that @pklaus suggested.

**Comment by danielballan** [comment]
Even in view of https://github.com/caproto/caproto/issues/609?

**Comment by tacaswell** [comment]
fair, I was going with "we have these kwargs so use them to avoid the double registration again" if we take the kwargs away then obviously option 1 is better ;)

The thing I feel strongly about is that we should not try to do any de-duplication of callbacks for the user (but we also shouldn't do any un-avoidable duplication).

**Comment by danielballan** [comment]
Yeah, strongly agree there. I played out the thought experiment of de-duplication just to think out loud.
