### ISSUE TITLE
caproto-IOC programming for dummies. 

### ISSUE THREAD

**Issue by toqduj** [caproto/caproto#721]
I've read a bit through the caproto IOC programming documentation and the IOC example code, but it's not quite clicking in place for me, and I could use some help wrapping my head around. 

Say I've got a very simple hotplate/stirrer (because I do), that can be controlled and read by sending commands over a socket connection (over my internal network to a 16-port network-to-serial converter that's connected to the hotplate). All this works and has been tested. 

So now I need to make an IOC with, as I understand, six PVs:
1. a PV for temperature set point (float read/write)
2. a PV for stirring set point (uint read/write)
3. a PV for actual temperature read-out (float read-only)
4. a PV for actual stirring speed read-out (uint read-only)
5. a PV Boolean for temperature control on/off
6. a PV Boolean for stirring control on/off

So I can take an example from the all_in_one.py example for this, also loading in my crappy communications "comms" class. As I understand things, I should make a class that inherits PVGroup and my comms class, point it at the right hotplate IP address and port number. Then I'm not so sure, but I should be initializing PVParameter instances and replacing the getter and setter functions with bits that actually communicate with the device? i.e. for each of my PVs, I should write something like:

```
    @pvproperty(value=20.0) # temperature
    async def temperature(self, instance): # <--- what is this "instance" here?
        logger.debug('read temperature set point')
        value = self.comms.sendReceive(self.ip, self.port, 'get temp_sp\n')
        return value # instance.value

    @temperature.putter
    async def newstyle(self, instance, value): # <-- what instance?
        logger.debug(f'setting temperature set point {value}')
        value = self.comms.sendReceive(self.ip, self.port, f'set temp_sp {value:3.2f}\n')
        return value
```

and that's pretty much it? or am I missing a whole host of good practices items to set and configure?

**Comment by klauer** [comment]
`all_in_one` may not be one of our best examples. We should probably go over that one of these days.
I'll try and break down what I think is "good practice" below and explain a bit about the arguments.

(Future docs TODO here, for sure!)

## putter arguments?
`getter` and `putter` functions can be reused among one or more pvproperties. 

For a given putter ("setter") handler method, the given arguments are then:
1. `self`, the `PVGroup` (the owner/parent of the pvproperty)
2. `instance`, the `ChannelData` tied to the `pvproperty` that was written to. This instance holds the current value, alarm instance, and other associated metadata.
3. `value`, the value written (after some processing to make it more user-friendly)

You are not required to use `instance` above: you could just as well use `self.temperature` in place of `instance`. These objects are guaranteed to be the same (`assert instance is self.temperature`), as this is the only pvproperty associated with the putter. In this specific scenario, it may be a matter of stylistic choice.

## General design

A few things on general design:

### Don't use `getter`

Generally speaking, you should not define a `getter`. This goes back to some of my original design decisions for how `pvproperty` instances work, and I really regret making it so easily accessible.
(Why? Well, inclusion of a getter can unfortunately make value monitoring less intuitive - each time a user runs `caget YOUR:PV`, the getter will be called. If you perform a `write` in the getter, that means that all other clients watching `YOUR:PV` will then see an update. If you add a few more clients to the mix, the update rate will seem even more arbitrary.)

### Single device communication
When talking to a single device and requesting a bunch of different information from it to update a single `PVGroup` to represent its status, I'd recommend the inclusion of a polling loop. 
1. An easy way to set this up is with the "SCAN" functionality: https://github.com/caproto/caproto/blob/master/caproto/ioc_examples/scan_rate.py#L10-L31
2. A real-life - but imperfect - example might be: https://github.com/pcdshub/fluke_985/blob/master/fluke_985/ioc.py#L544-L569

So each time your polling loop runs, you query the device for the necessary information. Then you update each of the pvproperties with the new data.

### Reactive design
Beyond that, most of what your IOC does should be in response to what the user requested, as in by setting a PV value (which caproto sees as a `putter` hook).

This matches up with what you have above - you'd want to send along a `set temp_sp {value}` when the user puts to `temperature` setpoint.

**Comment by toqduj** [comment]
Thanks for that clarification. Based on your Fluke example, I've now built two IOCs, one for a hotplate, another for an Arduino with relays and environmental sensors, and I'm starting to get the hang of what you did for a large part. However, I did define them in such a way which, according to the all_in_one example is the "old style": first instantiating a pvproperty and then (when necessary) defining a putter which sends the command to the device. 

They seem to be running OK for now, though there's still plenty of room for improvement. I wish there was a way to get a PV-tree however, to allow exploration of the entire CA bus or a given device. Perhaps a helper function caproto-tree would be a nice addition?

**Comment by klauer** [comment]
Thanks for the update, @toqduj. Glad you were able to make some more sense of it 👍 

I'm of the opinion that the old style is best for `pvproperty` in general. The "old" vs "new" naming comes from the Python `property` styles rather than something from caproto. That said, the "new" decorator syntax came out in 2.6 in 2008 - making them both pretty old 😁 

If you don't mind, I'd like to keep this issue open as a reminder - until we can get some of the above advice solidified into documentation.

The tree idea sounds interesting! Curious to hear what you think it'd look like.

As for what you can do right now: the easiest way to check it all may just be `$ camonitor (copy/paste all your IOC PVs)`. There is a separate package that the caproto developers have worked on called ophyd that intends to add that tree-level hierarchy from the client perspective, but it can be a bit difficult to use/understand at first. Link: https://github.com/bluesky/ophyd An extremely high-level gist of caproto->ophyd: one `PVGroup` would map onto an ophyd Device, with `EpicsSignal` "Components". Then, like the PVGroups, you could instantiate a device class with a PV prefix, and do things like `device.component.get()` for single-PV access or `device.get()` for full-device access.

**Comment by toqduj** [comment]
No problem keeping the issue open, @klauer. Before looking at EPICS, I was looking at ophyd to abstract our devices, until @ronpandolfi told us to look here as CA is a quite useful communications bus to have on the backend. 

Just a quick note on the Fluke example, it looks like the methods create_ioc(), create_parser() and main() could be abstracted out as well, these would be duplicated almost identically for every IOC that I'd write based on this example (I've only made two so far, but that's what it looks like, anyway). 

For the Tree, I was thinking of something for PV discovery, akin to the old DOS "tree" command. I don't always remember what I called my PVs, so a way of discovering them would be helpful if CA allows this (don't all IOCs broadcast their PVs regularly?). If we can then get a PV listing (optionally also with their values) that would help greatly. In my best ASCII-art representation:

```
root
|
|- [device 1]
|    |- [PVGroup 1]
|    |    L [PVparameter 1] : {value}
|    |    L [PVparameter 2] : {value}
|    |- [PVGroup 2]
|.        L [PVparameter 3] : {value}
|- [device 2]
|    L [PVparameter 4] : {value}
[...]
```
To make this useful, it should probably be made possible to limit the responses to something matching an expression, or only to go up to n levels deep...

**Comment by klauer** [comment]
As for implementing your device logic in ophyd vs caproto, caproto is certainly preferable as it effectively exposes your device state to the entire control system by way of CA instead of locking you into _just Python_ (which I'm pretty sure you understand here).

In your scenario I would encourage you to consider trying ophyd as the client-side interface (to your server-side caproto IOC). Making ophyd devices will allow you to easily use your caproto-backed PVs in scans and such with the bluesky suite of tools. Ron has used these tools quite a bit and can attest to that, for sure.

For making IOC after IOC, you might consider taking a look at the cookiecutter: https://github.com/caproto/cookiecutter-caproto-ioc (docs: https://caproto.github.io/caproto/v0.7.0/cookiecutter.html). We now even offer a `st.cmd`-like set of helper scripts that let you run these cookiecutter-generated IOCs with procServ or IOC manager (or systemd, etc.) [here](https://github.com/caproto/cookiecutter-caproto-ioc-startup).

The fluke one isn't a perfect example, though it was one of the first "full scale" ones I had written that actually talked to a device. The cookiecutter above may have some better patterns for you to base things off of.

For the tree, sadly CA does not broadcast PV names - or give you any way to introspect that tree structure. It's up to the client to search for them by name. There are additional tools out there like channelFinder that attempt to work around this, but I'm not familiar enough with them. The ophyd tooling would allow you to do something similar to your tree, but it does require you to match your `ophyd.Device` PVs with those that you wrote in the IOC.

**Comment by ronpandolfi** [comment]
@toqduj You might also take a look at Happi (promoting another of Ken's products 👍) for the purpose of tracking which devices are available. Since EPICS provides no device discovery mechanism (unfortunate IMO given its distributed nature), the next best thing is having a queryable database of devices. Happi is also a participant of the Pilot collaboration involving Alex Hexemer.
https://github.com/pcdshub/happi
