### ISSUE TITLE
Pyepics Compat Layer: caget_many ignores timeout

### ISSUE THREAD

**Issue by mcnanneyd** [caproto/caproto#805]
If the pyepics compat layer cannot connect to a PV, caget_many hangs indefinitely. There is a _timeout_ argument in this function, but it seems to be ignored. 

The pyepics approach to this case is to return None at the corresponding index in the return list for each disconnected (timed-out) PV. However, I do not believe this is the best approach. This is up for debate, but it would be nice if there was an option to raise an exception when a PV is not reached. 

For the sake of compatibility, I propose doing what we have done in a number of our pyepics applications, and having the caget_many function exhibit the pyepics behavior by default. I would like to add an additional _raises_ kwarg to this function, that is by default _False_. If this is set to True, any timeout encountered will raise an exception, rather than return None at the corresponding index. 

I will get working on a pull request for review. If anyone has any input for discussion, it would be appreciated!

**Comment by danielballan** [comment]
A PR ensuring that the `timeout` argument is not ignored would be very welcome.

We are in agreement that pyepics' choice to return `None` instead of raising an exception is problematic. It can lead to confusing failures downstream. I wouldn't want to go _too_ far extending the `pyepics_compat` module beyond the base pyepics interface --- as you say, the goal in compatibility --- but I think agree that extended it with a `raises` kwargs would be worthwhile.

While we are revisiting this, I wonder if the `caget_many` should be using [batched requests](https://caproto.github.io/caproto/v1.0.0/threading-client.html#batched-requests) internally. If I recall correctly, the batching feature was added to caproto's threading client after the `pyepics_compat` module was written, so it was not available to use in the original implementation of `pyepics_compat`.

**Comment by mcnanneyd** [comment]
Just submitted a PR! I am glad there are still some eyes on this project. You are right about this function not taking advantage of batched requests from the threading client.  I do think this may benefit from using the batched requests from the threading client, but I am not sure of the extent that it may improve performance. 

Completely up to you if you would like to try to work batched requests into this PR - or save it for a future PR. It looks like this additional change would require a decent amount of refactoring. Thanks for the quick response!

**Comment by eddybl** [comment]
I just tripped over the same issue. Is there a chance to get a bug fix release (1.0.1) for this? Or do you have a feeling of when there will be a new release? Depending on that I might need to look into creating a local work around

**Comment by klauer** [comment]
The squeaky wheel gets the grease

In the future, consider just doing a git-based install (`pip install git+https://github.com/caproto/caproto`) if repository maintainers don't have time to tag and release

**Comment by eddybl** [comment]
Thanks a lot!

Well, being able to install the main branch would not have been the problem, but I use caproto as a dependency in a site specific Python module, so this is where it gets tricky! ;)

(We also build a .deb version of caproto, but there it would have been less of an issue to just point to a specific commit)

**Comment by klauer** [comment]
Ah, sorry - I didn't know your background/facility/use/etc. That's neat about the Debian packaging, too.

I'm glad caproto is of use to you 👍
